environment:
  matrix:
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      deploy: ftp
    - source: https://cloud.r-project.org/src/base-prerelease/R-latest.tar.gz
      deploy: ftp
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz      
#    - source: https://cloud.r-project.org/src/base/R-latest.tar.gz
#      deploy: ftp

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

cache:
  - C:\miktex

on_success:
  - 7z a %target%-win.zip %builddir%\*.exe %builddir%\*.log %builddir%\*.html %builddir%\md5sum.txt %builddir%\SVN-REVISION %builddir%\README.*
  - appveyor PushArtifact %target%-win.zip
  - type %builddir%\check.log

on_finish:
  - 7z a logs.zip %builddir%\*.log
  - appveyor PushArtifact logs.zip
