
# # collect IP and username for rdp
# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: 0.1.0-{build}-{branch}

#
# Andre Mikulec
#
environment:
  matrix:
    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
      archive: r-patched
      cran: true
      MAKE_32BIT: 32-bit
      MAKE_DISTRIBUTION: distribution
      MARCHMTUNE: -march=broadwell
      MARCHMTUNENAME: CPU Build Broadwell
      DIST_BUILD: without Debugging Symbols
      DEPLOYNAME: Broadwell_NoDebug
    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
      archive: r-patched
      cran: true
      MAKE_32BIT: 32-bit DEBUG=T
      MAKE_DISTRIBUTION: distribution DEBUG=T
      MARCHMTUNE: -mtune=generic
      MARCHMTUNENAME: CPU Build Generic
      DIST_BUILD: with Debugging Symbols
      DEPLOYNAME: Generic_Debug

# #
# #    - source: https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
# #      RTOOLS_VERSION: 35
# #      archive: r-release
#     - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
#       archive: r-devel
#       cran: true
# #    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
#     - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
#       archive: r-patched
#       cran: true

install:
  - ps: |
      Write-Output "Begin install: environment variables"
      Get-ChildItem Env:
      Set-PSDebug -Trace 2
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
      Write-Output "End   install: environment variables"
      Get-ChildItem Env:

  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - echo on
  - echo begin  .\scripts\build.bat R-source.tar.gz 32
  - echo Begin build_script: BEFORE build.bat R-source.tar.gz 32 environment variables
  - set
  - echo End   build_script: BEFORE build.bat R-source.tar.gz 32 environment variables
  - .\scripts\build.bat R-source.tar.gz 32
  - echo Begin build_script: AFTER  build.bat R-source.tar.gz 32 environment variables
  - set
  - echo End   build_script: AFTER  build.bat R-source.tar.gz 32 environment variables
  - echo end    .\scripts\build.bat R-source.tar.gz 32
  - echo begin  .\scripts\build.bat R-source.tar.gz 64
  - echo Begin build_script: BEFORE build.bat R-source.tar.gz 64 environment variables
  - set
  - echo End   build_script: BEFORE build.bat R-source.tar.gz 64 environment variables
  - .\scripts\build.bat R-source.tar.gz 64
  - echo Begin build_script: AFTER  build.bat R-source.tar.gz 64 environment variables
  - set
  - echo End   build_script: AFTER  build.bat R-source.tar.gz 64 environment variables
  - echo end    .\scripts\build.bat R-source.tar.gz 64
  - cd %builddir%
  - echo begin md5sum %target%-win.exe > md5sum.txt.%target%
  - time /t
  - md5sum %target%-win.exe > md5sum.txt.%target%
  - echo end   md5sum %target%-win.exe > md5sum.txt.%target%
  - cd %startdir%
  - echo begin 7z of %target%-win.zip
  - 7z a %target%-win.zip %builddir%\%target%-win.exe %builddir%\md5sum.txt.%target% %builddir%\*.log %builddir%\*.html %builddir%\SVN-REVISION.* %builddir%\README.*
  - echo end   7z of %target%-win.zip
  - echo begin 7z of %target%-FEobjs32.zip
  - time /t
  - 7z a %target%-FEobjs32.zip %builddir%\R-source-win32\src\gnuwin32\front-ends\*.o
  - echo end   7z of %target%-FEobjs32.zip
  - echo begin 7z of %target%-FEobjs64.zip
  - 7z a %target%-FEobjs64.zip %builddir%\R-source-win64\src\gnuwin32\front-ends\*.o
  - echo end   7z of %target%-FEobjs64.zip
  - echo begin 7z of  logs.zip
  - 7z a              logs.zip %builddir%\*.log
  - echo end   7z of  logs.zip
  - echo begin 7z of "%archive%-%target%-%revision%-%DEPLOYNAME%.zip"
  - 7z a              %archive%-%target%-%revision%-%DEPLOYNAME%.zip logs.zip %target%-FEobjs64.zip %target%-FEobjs32.zip %target%-win.zip
  - echo end   7z of "%archive%-%target%-%revision%-%DEPLOYNAME%.zip"
  - echo End build_script: environment variables
  - set

artifacts:
  - path: "%archive%-%target%-%revision%-%DEPLOYNAME%.zip"
    name: "%archive%-%target%-%revision%-%DEPLOYNAME%.zip"

on_finish:
  - 7z a logs.zip %builddir%\*.log
  - appveyor PushArtifact logs.zip

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

deploy:
  release: "$(APPVEYOR_PROJECT_SLUG)_$(appveyor_build_version)_%archive%_%target%_%revision%_%DEPLOYNAME%"
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  artifact: "%archive%-%target%-%revision%-%DEPLOYNAME%.zip"
  draft: false
  prerelease: false
  on:
    branch: master

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# # remove locking file from the desktop
