environment:
  matrix:
    - source: https://cloud.r-project.org/src/base-prerelease/R-latest.tar.gz
      upload: true
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      upload: true
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz      
#    - source: https://cloud.r-project.org/src/base/R-latest.tar.gz
#      deploy: ftp

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

after_build:
  - 7z a %target%-win.zip %builddir%\*.exe %builddir%\*.log %builddir%\*.html %builddir%\md5sum.txt %builddir%\SVN-REVISION %builddir%\README.*

artifacts:
  - path: "%target%-win.zip"
    name: Installer Bundle  

on_success:
  - type %builddir%\check.log

on_finish:
  - 7z a logs.zip %builddir%\*.log
  - appveyor PushArtifact logs.zip

deploy:
  provider: FTP
  protocol: ftps
  host: ftp.opencpu.org
  username: upload
  password:
    secure: u7Vv/A5W5RiRQ0sJ6QmKvN/g6h3J9y9ujuqZi0uDAAY=
  folder: /archive/$(target)/$(revision)
  application: "%target%-win.zip"
  on:
    upload: true
  beta: true
  debug: true