environment:
  matrix:
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      version: R-devel
    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
      version: R-patched
    - source: https://cran.r-project.org/src/base/R-3/R-3.4.2.tar.gz
      version: R-3.4.2

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "${env:version}.tar.gz"
  - build.bat %version% 32
  - build.bat %version% 64

cache:
  - C:\miktex

on_success:
  - 7z a %version%-win.zip ..\BUILD\*.exe ..\BUILD\*.log ..\BUILD\*.html ..\BUILD\md5sum.txt ..\BUILD\SVN-REVISION ..\BUILD\README.*
  - appveyor PushArtifact %version%-win.zip
  - type ..\BUILD\check.log

on_finish:
  - 7z a logs.zip ..\BUILD\*.log
  - appveyor PushArtifact logs.zip
