
version: 0.1.0-{build}-{branch}

environment:
  matrix:
#    - source: https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
#      RTOOLS_VERSION: 35
#      archive: r-release    
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      archive: r-devel
      cran: true
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
      archive: r-patched
      cran: true

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - echo begin  .\scripts\build.bat R-source.tar.gz 32
  - time
  - .\scripts\build.bat R-source.tar.gz 32
  - time
  - echo end    .\scripts\build.bat R-source.tar.gz 32
  - echo begin  .\scripts\build.bat R-source.tar.gz 64
  - time
  - .\scripts\build.bat R-source.tar.gz 64
  - time
  - echo end    .\scripts\build.bat R-source.tar.gz 64
  - cd %builddir%
  - echo begin md5sum %target%-win.exe > md5sum.txt.%target%
  - time
  - md5sum %target%-win.exe > md5sum.txt.%target%
  - time
  - echo end   md5sum %target%-win.exe > md5sum.txt.%target%
  - cd %startdir%
  - echo begin 7z of %target%-win.zip
  - time
  - 7z a %target%-win.zip      %builddir%\%target%-win.exe %builddir%\md5sum.txt.%target% %builddir%\*.log %builddir%\*.html %builddir%\SVN-REVISION.* %builddir%\README.*
  - time
  - echo end   7z of %target%-win.zip
  - echo begin 7z of %target%-FEobjs32.zip
  - time
  - 7z a %target%-FEobjs32.zip %builddir%\R-source-win32\src\gnuwin32\front-ends\*.o
  - time
  - echo end   7z of %target%-FEobjs32.zip
  - echo begin 7z of %target%-FEobjs64.zip
  - time
  - 7z a %target%-FEobjs64.zip %builddir%\R-source-win64\src\gnuwin32\front-ends\*.o
  - time
  - echo end   7z of %target%-FEobjs64.zip
  - echo begin 7z of logs.zip
  - time
  - 7z a logs.zip              %builddir%\*.log
  - time
  - echo end   7z of logs.zip
  - echo begin 7z of %archive%-%target%-win-pkgdebug.zip
  - time
  - 7z a %archive%-%target%-win-pkgdebug.zip logs.zip %target%-FEobjs64.zip %target%-FEobjs32.zip %target%-win.zip 
  - time
  - echo end   7z of %archive%-%target%-win-pkgdebug.zip

artifacts:
  - path: "%archive%-%target%-win-pkgdebug.zip"
    name: "%archive%-%target%-win-pkgdebug.zip"

# too much time?
# too big for github?
# too much network bandwidth usage?
# something else?
# 
# deploy:
#   release: "$(APPVEYOR_PROJECT_SLUG)_$(appveyor_build_version)_%archive%_%target%_%revision%"
#   provider: GitHub
#   auth_token:
#     secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
#   artifact: "%archive%-%target%-win-pkgdebug.zip"
#   draft: false
#   prerelease: false
#   on:
#     branch: master
#     # I do not care about tags
#     appveyor_repo_tag: false

