# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  - ps: $ErrorActionPreference = "Stop"
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest https://stat.ethz.ch/R/daily/R-devel.tar.gz -OutFile "R-devel.tar.gz"
  - r-devel.bat

artifacts:
  - path: '*.log'
    name: Logs

cache:
  - C:\miktex

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
