environment:
  matrix:
#    - source: https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
#      RTOOLS_VERSION: 35
#      archive: r-release    
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
      archive: r-devel
      cran: true
#    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
    - source: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
      archive: r-patched
      cran: true

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

artifacts:
  - path: ..\BUILD
    name: $(APPVEYOR_PROJECT_SLUG)_Dist_%archive%_%target%_%revision%

deploy:
  release: $(APPVEYOR_PROJECT_SLUG)_$(appveyor_build_version)_%archive%_%target%_%revision%
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  artifact: $(APPVEYOR_PROJECT_SLUG)_Dist_%archive%_%target%_%revision%
  draft: false
  prerelease: false
  on:
    branch: master
    # I do not care about tags
    appveyor_repo_tag: false
