environment:
  matrix:
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
    - source: https://cran.r-project.org/src/base/R-3/R-3.4.2.tar.gz

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "$env:source" -OutFile "R-source.tar.gz"
  - build.bat R-source 32
  - build.bat R-source 64

cache:
  - C:\miktex

on_success:
  - 7z a installer.zip ..\BUILD\*.exe
  - appveyor PushArtifact installer.zip

on_finish:
  - 7z a logs.zip ..\BUILD\*.log
  - appveyor PushArtifact logs.zip
