environment:
  matrix:
    - source: https://stat.ethz.ch/R/daily/R-devel.tar.gz
    - source: https://stat.ethz.ch/R/daily/R-patched.tar.gz
    - source: https://cran.r-project.org/src/base/R-latest.tar.gz

install:
  - ps: |
      Import-Module '.\scripts\appveyor-tool.ps1'
      SetTimezone
      InstallMiktex
      InstallPerl
      InstallInno
      InstallRtools
  - git submodule update --init

build_script:
  - ps: Invoke-WebRequest "${env:source}" -OutFile "R-source.tar.gz"
  - .\scripts\build.bat R-source.tar.gz 32
  - .\scripts\build.bat R-source.tar.gz 64

cache:
  - C:\miktex

on_success:
  - 7z a %target%-win.zip ..\BUILD\*.exe ..\BUILD\*.log ..\BUILD\*.html ..\BUILD\md5sum.txt ..\BUILD\SVN-REVISION ..\BUILD\README.*
  - appveyor PushArtifact %target%-win.zip
  - type ..\BUILD\check.log

on_finish:
  - 7z a logs.zip ..\BUILD\*.log
  - appveyor PushArtifact logs.zip
